version: '3'

services:
    app:
        build: ./docker/app/
        container_name: 'app'
        working_dir: /var/www
        volumes:
            - ./src:/var/www
            - ./docker/app/conf.d:/usr/local/etc/php/conf.d
        ports:
            - 10000:8000
        depends_on:
            - db
    db:
        image: mysql:5.7
        container_name: 'db'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: learning
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
